---
# file: dbservers.yml
- hosts: dbservers
  sudo: yes

  roles:
    - role: common
    - role: resmo.ntp
    - role: ANXS.monit
      monit_notify_email: "{{notify_email}}"
    - role: ANXS.postgresql
      monit_protection: true
      postgresql_version: "{{postgresql_version}}"
      postgresql_users:
        - name: "{{database_user}}"
          pass: "{{database_password}}"
          encrypted: no
      postgresql_databases: "{{my_postgresql_databases}}"
      postgresql_user_privileges: "{{my_postgresql_user_privileges}}"
      postgresql_pg_hba_custom: "{{my_postgresql_pg_hba_custom}}"
      postgresql_listen_addresses:
        - "*"

    - role: Stouts.wale
