---
- name: Install everything needed for a postgres 9.4 server
  hosts: dev
  sudo: yes
  vars:
    database_name: "myapp"
    database_user: "deploy"
    database_password: "test1234"
    database_hostname: "localhost"
    database_port: 5432
    database_addresses: "0.0.0.0/0"

  roles:
    - role: resmo.ntp

    - role: ANXS.monit
      monit_notify_email: "sysadmin.email@example.org"

    - role: ANXS.postgresql
      monit_protection: true
      postgresql_version: 9.4
      postgresql_databases:
        - name: "{{database_name}}"
      postgresql_users:
        - name: "{{database_user}}"
          pass: "{{database_password}}"
          encrypted: no
      postgresql_user_privileges:
        - name: "{{database_user}}"
          db: "{{database_name}}"
          priv: "ALL"
      postgresql_pg_hba_custom:
        - type: host
          database: "{{database_name}}"
          user: "{{database_user}}"
          address: "{{database_addresses}}"
          method: 'md5'
          comment: "Allow remote access to '{{database_name}}' database by '{{database_user}}' user"
      postgresql_listen_addresses:
        - "*"

    - role: Stouts.wale
    # - role: joshualund.ufw
    #   ufw_connection_rate_limits:
    #     - {port: 22, protocol: tcp}
    #   ufw_whitelisted_ports:
    #     - {port: 22, protocol: tcp}
    #     - {port: 80, protocol: tcp}
    #     - {port: 443, protocol: tcp}