---
- name: Install everything needed for a postgres 9.4 server
  hosts: '{{ target }}'
  sudo: yes
  vars:
    database_name: "myapp"
    database_user: "deploy"
    database_password: "test1234"
    database_hostname: "localhost"
    database_port: 5432
    database_addresses: "0.0.0.0/0"

    postgresql_wal_level: hot_standby
    postgresql_archive_mode: yes
    postgresql_archive_command: /etc/wale/wale.sh wal-push %p
    postgresql_archive_timeout: 60

    backup_s3_bucket: change-me
    backup_s3_access_key_id: change-me
    backup_s3_secret_access_key: change-me

    postgresql_version: 9.4

# Stouts.wale
# ===========
    wale_aws_access_key_id: "{{backup_s3_access_key_id}}"
    wale_aws_secret_access_key: "{{backup_s3_secret_access_key}}"
    wale_aws_s3_prefix: "s3://{{backup_s3_bucket}}/{{inventory_hostname}}"
    wale_cron:
      - { schedule: "0 2 * * *", cmd: "backup-push /var/lib/postgresql/{{postgresql_version}}/main" }

  tasks:
    - name: Install python six package - version >= v1.7.0 - which is required by wal-e
      pip: name=six state=latest

  roles:
    - role: resmo.ntp

    - role: ANXS.monit
      monit_notify_email: "sysadmin.email@example.org"

    - role: ANXS.postgresql
      monit_protection: true
      postgresql_version: "{{postgresql_version}}"
      postgresql_databases:
        - name: "{{database_name}}"
      postgresql_users:
        - name: "{{database_user}}"
          pass: "{{database_password}}"
          encrypted: no
      postgresql_user_privileges:
        - name: "{{database_user}}"
          db: "{{database_name}}"
          priv: "ALL"
      postgresql_pg_hba_custom:
        - type: host
          database: "{{database_name}}"
          user: "{{database_user}}"
          address: "{{database_addresses}}"
          method: 'md5'
          comment: "Allow remote access to '{{database_name}}' database by '{{database_user}}' user"
      postgresql_listen_addresses:
        - "*"

    - role: Stouts.wale
    # - role: joshualund.ufw
    #   ufw_connection_rate_limits:
    #     - {port: 22, protocol: tcp}
    #   ufw_whitelisted_ports:
    #     - {port: 22, protocol: tcp}
    #     - {port: 80, protocol: tcp}
    #     - {port: 443, protocol: tcp}