# file: common/tasks/main.yml

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Apt safe upgrade
  apt: upgrade=safe

- name: Check if a reboot is required
  register: reboot_required
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the server
  command: /sbin/reboot
  when: reboot_required.stat.exists == true

- name: Wait for server to come back
  local_action: wait_for host={{ inventory_hostname }} delay=1 timeout=90
  tags: reboot
  sudo: false
  when: reboot_required.stat.exists == true
